### ISSUE TITLE
KeyError:0 when baking HMM model

### ISSUE THREAD

**Issue by zoethomson** [dbountouridis/MusicProfileHMMs#1]
Hi,

I am trying to use this package to train an HMM model using genetic sequences. Everything is working fine until I try to bake the model using krogh.profileHMM per the README as follows:

model, columnsIsMatchState = krogh.profileHMM(msa, alphabet=alphabet,gapRatiotoMatchStates=grms, pseudoCountTransition=pct,
	sequenceWeight=sw, pseudoEmissionCount=pec, 
	plot_=False, uniformInsertionProbs=True, nullEmission=EmissionProbabilities)

Using breakpoints I can see that the model is being generated, although I can't see it in the variable explorer:

> model
> <yahmm.yahmm.Model object at 0x7f9468638e20>

Here is the error I get:

Traceback (most recent call last):

  File "<ipython-input-2-f806e6d6e95f>", line 61, in <module>
    plot_=False, uniformInsertionProbs=True, nullEmission=EmissionProbabilities)

  File "/Users/thomson/Documents/Y06/BME808/LABS/project/MusicProfileHMMs-master/kroghProfileHMM.py", line 362, in profileHMM
    uniformInsertionProbs, nullEmission)

  File "/Users/thomson/Documents/Y06/BME808/LABS/project/MusicProfileHMMs-master/kroghProfileHMM.py", line 331, in createProfileHMMfromStructure
    model.bake()

  File "yahmm/yahmm.pyx", line 2330, in yahmm.yahmm.Model.bake

  File "/Users/thomson/opt/anaconda3/envs/py27/lib/python2.7/site-packages/networkx/classes/reportviews.py", line 178, in __getitem__
    return self._nodes[n]

KeyError: 0

Any ideas why this KeyError is being thrown from model.bake(), and how to resolve it?

**Comment by pixel-girl** [comment]
Hello I know this is really random but we also are using this code did you by any chance figure out the problem and how to resolve it. We are facing the same issue
If so, please feel free to contact me through my email
aya.baydoun03@lau.edu
